In [20]:
import pandas as pd

data = pd.read_csv('Market_Basket.csv',header=None)

In [21]:
data.shape

(7501, 20)

In [22]:
data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
import string

transactionsList = []

for customer in range(0,7500):
    transaction = []
    for item in range(0,20):
        if str(data.values[customer,item]) != 'nan':
            transaction.append(str(data.values[customer,item]))
    transactionsList.append(transaction)
#print(transactionsList)

In [159]:
from efficient_apriori import apriori
itemsets, rules = apriori(transactionsList, min_support=0.03, min_confidence=0.2,max_length=3)
print(len(rules))

27

In [160]:
for rule in rules:
    print(rule)
    print()

{chocolate} -> {eggs} (conf: 0.203, supp: 0.033, lift: 1.128, conv: 1.029)

{french fries} -> {chocolate} (conf: 0.201, supp: 0.034, lift: 1.228, conv: 1.047)

{chocolate} -> {french fries} (conf: 0.210, supp: 0.034, lift: 1.228, conv: 1.049)

{milk} -> {chocolate} (conf: 0.248, supp: 0.032, lift: 1.513, conv: 1.112)

{mineral water} -> {chocolate} (conf: 0.221, supp: 0.053, lift: 1.348, conv: 1.073)

{chocolate} -> {mineral water} (conf: 0.321, supp: 0.053, lift: 1.348, conv: 1.122)

{spaghetti} -> {chocolate} (conf: 0.225, supp: 0.039, lift: 1.374, conv: 1.079)

{chocolate} -> {spaghetti} (conf: 0.239, supp: 0.039, lift: 1.374, conv: 1.086)

{french fries} -> {eggs} (conf: 0.213, supp: 0.036, lift: 1.186, conv: 1.042)

{eggs} -> {french fries} (conf: 0.203, supp: 0.036, lift: 1.186, conv: 1.040)

{milk} -> {eggs} (conf: 0.238, supp: 0.031, lift: 1.323, conv: 1.076)

{mineral water} -> {eggs} (conf: 0.214, supp: 0.051, lift: 1.190, conv: 1.043)

{eggs} -> {mineral water} (conf: 0.284, supp: 0.051, lift: 1.190, conv: 1.063)

{spaghetti} -> {eggs} (conf: 0.210, supp: 0.037, lift: 1.168, conv: 1.038)

{eggs} -> {spaghetti} (conf: 0.203, supp: 0.037, lift: 1.168, conv: 1.037)

{frozen vegetables} -> {mineral water} (conf: 0.375, supp: 0.036, lift: 1.572, conv: 1.218)

{green tea} -> {mineral water} (conf: 0.235, supp: 0.031, lift: 0.986, conv: 0.996)

{ground beef} -> {mineral water} (conf: 0.417, supp: 0.041, lift: 1.747, conv: 1.305)

{spaghetti} -> {ground beef} (conf: 0.225, supp: 0.039, lift: 2.291, conv: 1.164)

{ground beef} -> {spaghetti} (conf: 0.399, supp: 0.039, lift: 2.291, conv: 1.374)

{mineral water} -> {milk} (conf: 0.201, supp: 0.048, lift: 1.554, conv: 1.090)

{milk} -> {mineral water} (conf: 0.370, supp: 0.048, lift: 1.554, conv: 1.210)

{spaghetti} -> {milk} (conf: 0.204, supp: 0.035, lift: 1.572, conv: 1.093)

{milk} -> {spaghetti} (conf: 0.274, supp: 0.035, lift: 1.572, conv: 1.137)

{pancakes} -> {mineral water} (conf: 0.355, supp: 0.034, lift: 1.488, conv: 1.180)

{spaghetti} -> {mineral water} (conf: 0.343, supp: 0.060, lift: 1.439, conv: 1.159)

{mineral water} -> {spaghetti} (conf: 0.251, supp: 0.060, lift: 1.439, conv: 1.102)